# Auto-generated by SW2GZ.
import os
import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('three_dof_arm_description')
    xacro_path = os.path.join(pkg_share, 'urdf', 'three_dof_arm_description.urdf.xacro')
    robot_desc = xacro.process_file(xacro_path).toxml()

    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher',
               output='screen', parameters=[{'robot_description': robot_desc, 'use_sim_time': False}])
    jsp = Node(package='joint_state_publisher_gui', executable='joint_state_publisher_gui')
    rviz = Node(package='rviz2', executable='rviz2', arguments=[
        '-d', os.path.join(pkg_share, 'config', 'rviz.rviz')])

    return LaunchDescription([rsp, jsp, rviz])
