/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.
*/
using System.Linq;
using SW2GZ.Ros2;
using Xunit;

namespace SW2GZ.Test.Writers
{
    public class TestPackageXmlV3Writer : WriterTestBase
    {
        private PackageXmlV3Writer.Input MakeInput(GzVersion gz = GzVersion.Harmonic,
                                                   Ros2Distro distro = Ros2Distro.Jazzy)
        {
            return new PackageXmlV3Writer.Input
            {
                PackageName = "my_robot_description",
                Version = "0.1.0",
                Description = "Auto-generated by SW2GZ",
                Maintainer = "aryan",
                MaintainerEmail = "aryan@example.com",
                License = "Apache-2.0",
                Profile = new TargetProfile { Gz = gz, Ros2 = distro },
            };
        }

        [Fact]
        [Trait("Category", "Unit")]
        public void EmitsFormat3RootWithCorrectMetadata()
        {
            new PackageXmlV3Writer(MakeInput()).Write(TempDir);

            Assert.True(Exists("package.xml"));
            var doc = LoadXml("package.xml");
            Assert.Equal("package", doc.Root.Name.LocalName);
            Assert.Equal("3", doc.Root.Attribute("format").Value);
            Assert.Equal("my_robot_description", doc.Root.Element("name").Value);
            Assert.Equal("0.1.0", doc.Root.Element("version").Value);
            Assert.Equal("Apache-2.0", doc.Root.Element("license").Value);
            Assert.Equal("aryan", doc.Root.Element("maintainer").Value);
            Assert.Equal("aryan@example.com",
                doc.Root.Element("maintainer").Attribute("email").Value);
        }

        [Fact]
        [Trait("Category", "Unit")]
        public void IncludesAmentCmakeBuildtool()
        {
            new PackageXmlV3Writer(MakeInput()).Write(TempDir);
            var doc = LoadXml("package.xml");
            var buildtools = doc.Root.Elements("buildtool_depend")
                .Select(e => e.Value).ToList();
            Assert.Contains("ament_cmake", buildtools);
        }

        [Fact]
        [Trait("Category", "Unit")]
        public void IncludesRosGzPackagesForHarmonicJazzy()
        {
            new PackageXmlV3Writer(MakeInput(GzVersion.Harmonic, Ros2Distro.Jazzy)).Write(TempDir);
            var doc = LoadXml("package.xml");
            var execDeps = doc.Root.Elements("exec_depend").Select(e => e.Value).ToList();
            Assert.Contains("ros_gz_sim", execDeps);
            Assert.Contains("ros_gz_bridge", execDeps);
            Assert.Contains("gz_ros2_control", execDeps);
            Assert.Contains("robot_state_publisher", execDeps);
            Assert.Contains("joint_state_publisher_gui", execDeps);
            Assert.Contains("xacro", execDeps);
            Assert.Contains("rviz2", execDeps);
        }

        [Fact]
        [Trait("Category", "Unit")]
        public void IncludesRosIgnPackagesForFortressHumble()
        {
            new PackageXmlV3Writer(MakeInput(GzVersion.Fortress, Ros2Distro.Humble)).Write(TempDir);
            var doc = LoadXml("package.xml");
            var execDeps = doc.Root.Elements("exec_depend").Select(e => e.Value).ToList();
            Assert.Contains("ros_ign_gazebo", execDeps);
            Assert.Contains("ros_ign_bridge", execDeps);
            Assert.Contains("ign_ros2_control", execDeps);
        }
    }
}
