/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.

Emits config/ros_gz_bridge.yaml — the parameter_bridge config consumed by
the parameter_bridge node launched from gz_sim.launch.py (T13). The
joint_state gz_topic_name uses the package name to match the spawn
`-name <packageName>` argument — fixes v1.0 export bug 6 (alignment).

Locked to world "empty" (matches T12 SdfWorldWriter).
*/
using System;
using System.Text;

namespace SW2GZ.Gz
{
    public static class RosGzBridgeYaml
    {
        public static string Write(string packageName)
        {
            if (string.IsNullOrWhiteSpace(packageName))
                throw new ArgumentException("packageName must not be null or whitespace.", nameof(packageName));

            var sb = new StringBuilder();
            sb.AppendLine("# Auto-generated by SW2GZ. ros_gz_bridge default topic bridge.");
            sb.AppendLine("- ros_topic_name: \"/clock\"");
            sb.AppendLine("  gz_topic_name: \"/clock\"");
            sb.AppendLine("  ros_type_name: \"rosgraph_msgs/msg/Clock\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Clock\"");
            sb.AppendLine("  direction: GZ_TO_ROS");
            sb.AppendLine();
            sb.AppendLine("- ros_topic_name: \"/joint_states\"");
            sb.AppendLine($"  gz_topic_name: \"/world/empty/model/{packageName}/joint_state\"");
            sb.AppendLine("  ros_type_name: \"sensor_msgs/msg/JointState\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Model\"");
            sb.AppendLine("  direction: GZ_TO_ROS");
            sb.AppendLine();
            sb.AppendLine("- ros_topic_name: \"/tf\"");
            sb.AppendLine("  gz_topic_name: \"/tf\"");
            sb.AppendLine("  ros_type_name: \"tf2_msgs/msg/TFMessage\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Pose_V\"");
            sb.AppendLine("  direction: GZ_TO_ROS");
            return sb.ToString();
        }
    }
}
