/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.
*/
using System.IO;
using System.Text;

namespace SW2GZ.Gz
{
    public class RosGzBridgeYaml
    {
        public void Write(string outputDir, string fileName = "ros_gz_bridge.yaml")
        {
            Directory.CreateDirectory(outputDir);
            var sb = new StringBuilder();
            sb.AppendLine("# Auto-generated by SW2GZ. ros_gz_bridge default topic bridge.");
            sb.AppendLine("- ros_topic_name: \"/clock\"");
            sb.AppendLine("  gz_topic_name: \"/clock\"");
            sb.AppendLine("  ros_type_name: \"rosgraph_msgs/msg/Clock\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Clock\"");
            sb.AppendLine("  direction: GZ_TO_ROS");
            sb.AppendLine();
            sb.AppendLine("- ros_topic_name: \"/joint_states\"");
            sb.AppendLine("  gz_topic_name: \"/world/empty/model/robot/joint_state\"");
            sb.AppendLine("  ros_type_name: \"sensor_msgs/msg/JointState\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Model\"");
            sb.AppendLine("  direction: GZ_TO_ROS");
            sb.AppendLine();
            sb.AppendLine("- ros_topic_name: \"/tf\"");
            sb.AppendLine("  gz_topic_name: \"/tf\"");
            sb.AppendLine("  ros_type_name: \"tf2_msgs/msg/TFMessage\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Pose_V\"");
            sb.AppendLine("  direction: GZ_TO_ROS");
            File.WriteAllText(Path.Combine(outputDir, fileName), sb.ToString());
        }
    }
}
