/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.

Emits config/ros_gz_bridge.yaml — the parameter_bridge config consumed by
the parameter_bridge node launched from gz_sim.launch.py (T13). The
joint_state gz_topic_name uses the package name to match the spawn
`-name <packageName>` argument — fixes v1.0 export bug 6 (alignment).

Locked to world "empty" (matches T12 SdfWorldWriter).

P6-data — Write(packageName, sensors) overload appends one bridge entry
per sensor (ROS↔Gz type pair per SensorKind). The legacy single-arg
overload delegates with an empty sensor list, so the clock/joint_state/
tf header is byte-identical for the empty case (golden parity preserved).
*/
using System;
using System.Collections.Generic;
using System.Security;
using System.Text;
using SW2GZ.Build.Model;

namespace SW2GZ.Gz
{
    public static class RosGzBridgeYaml
    {
        public static string Write(string packageName) =>
            Write(packageName, Array.Empty<SensorDef>());

        public static string Write(string packageName, IReadOnlyList<SensorDef> sensors)
        {
            if (string.IsNullOrWhiteSpace(packageName))
                throw new ArgumentException("packageName must not be null or whitespace.", nameof(packageName));
            if (sensors == null) throw new ArgumentNullException(nameof(sensors));

            var sb = new StringBuilder();
            sb.AppendLine("# Auto-generated by SW2GZ. ros_gz_bridge default topic bridge.");
            sb.AppendLine("- ros_topic_name: \"/clock\"");
            sb.AppendLine("  gz_topic_name: \"/clock\"");
            sb.AppendLine("  ros_type_name: \"rosgraph_msgs/msg/Clock\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Clock\"");
            sb.AppendLine("  direction: GZ_TO_ROS");
            sb.AppendLine();
            sb.AppendLine("- ros_topic_name: \"/joint_states\"");
            sb.AppendLine($"  gz_topic_name: \"/world/empty/model/{packageName}/joint_state\"");
            sb.AppendLine("  ros_type_name: \"sensor_msgs/msg/JointState\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Model\"");
            sb.AppendLine("  direction: GZ_TO_ROS");
            sb.AppendLine();
            sb.AppendLine("- ros_topic_name: \"/tf\"");
            sb.AppendLine("  gz_topic_name: \"/tf\"");
            sb.AppendLine("  ros_type_name: \"tf2_msgs/msg/TFMessage\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Pose_V\"");
            sb.AppendLine("  direction: GZ_TO_ROS");

            // No trailing newline for empty sensors -> byte-parity with legacy.
            if (sensors.Count == 0)
                return sb.ToString();

            foreach (SensorDef s in sensors)
            {
                (string rosType, string gzType) = MapTypes(s.Kind);
                string topic = SecurityElement.Escape(s.Topic);
                sb.AppendLine();
                sb.AppendLine($"- ros_topic_name: \"{topic}\"");
                sb.AppendLine($"  gz_topic_name: \"{topic}\"");
                sb.AppendLine($"  ros_type_name: \"{rosType}\"");
                sb.AppendLine($"  gz_type_name: \"{gzType}\"");
                sb.AppendLine("  direction: GZ_TO_ROS");
            }
            return sb.ToString();
        }

        private static (string Ros, string Gz) MapTypes(SensorKind kind) => kind switch
        {
            SensorKind.Imu         => ("sensor_msgs/msg/Imu",            "gz.msgs.IMU"),
            SensorKind.GpuLidar    => ("sensor_msgs/msg/LaserScan",      "gz.msgs.LaserScan"),
            SensorKind.Camera      => ("sensor_msgs/msg/Image",          "gz.msgs.Image"),
            SensorKind.DepthCamera => ("sensor_msgs/msg/Image",          "gz.msgs.Image"),
            SensorKind.ForceTorque => ("geometry_msgs/msg/WrenchStamped","gz.msgs.Wrench"),
            SensorKind.Contact     => ("ros_gz_interfaces/msg/Contacts", "gz.msgs.Contacts"),
            SensorKind.Navsat      => ("sensor_msgs/msg/NavSatFix",      "gz.msgs.NavSat"),
            _ => throw new InvalidOperationException($"Unhandled SensorKind: {kind}"),
        };
    }
}
