/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.

World-mode ros_gz_bridge config (config consumed by the parameter_bridge node
in launch_world.py). Unlike the robot-shaped RosGzBridgeYaml (which bridges
/joint_states + /tf keyed to a spawned robot name), a World has no robot — so
this writer emits only the world-level topics:

  /clock    GZ→ROS   always — so use_sim_time advances.
  /cmd_vel  ROS→GZ   only when teleop is enabled (KeyPublisher/TriggeredPublisher
                     publish a Gz Twist on /cmd_vel; bridging lets an external
                     ROS teleop node drive the same in-sim topic).

Locked to ROS 2 Jazzy + Gz Harmonic message types.
*/
using System.Text;

namespace SW2GZ.Gz
{
    public static class WorldBridgeYaml
    {
        public static string Write(bool teleop)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Auto-generated by SW2GZ. World ros_gz_bridge config.");
            sb.AppendLine("- ros_topic_name: \"/clock\"");
            sb.AppendLine("  gz_topic_name: \"/clock\"");
            sb.AppendLine("  ros_type_name: \"rosgraph_msgs/msg/Clock\"");
            sb.AppendLine("  gz_type_name: \"gz.msgs.Clock\"");
            sb.AppendLine("  direction: GZ_TO_ROS");

            // Teleop: the in-sim KeyPublisher/TriggeredPublisher publishes a Gz
            // Twist on /cmd_vel. Bridge it ROS→GZ so an external ROS teleop can
            // command the same topic.
            if (teleop)
            {
                sb.AppendLine();
                sb.AppendLine("- ros_topic_name: \"/cmd_vel\"");
                sb.AppendLine("  gz_topic_name: \"/cmd_vel\"");
                sb.AppendLine("  ros_type_name: \"geometry_msgs/msg/Twist\"");
                sb.AppendLine("  gz_type_name: \"gz.msgs.Twist\"");
                sb.AppendLine("  direction: ROS_TO_GZ");
            }

            return sb.ToString();
        }
    }
}
