/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.
*/
using System.IO;

namespace SW2GZ.Ros2
{
    public class LaunchPyWriter
    {
        public class Input
        {
            public string PackageName { get; set; }
            public string XacroFileName { get; set; }
            public string WorldFileName { get; set; } = "empty.sdf";
            public TargetProfile Profile { get; set; }
        }

        private readonly Input _in;
        public LaunchPyWriter(Input input) { _in = input; }

        public void Write(string outputDir)
        {
            Directory.CreateDirectory(outputDir);
            File.WriteAllText(Path.Combine(outputDir, "display.launch.py"), Display());
            File.WriteAllText(Path.Combine(outputDir, "gz_sim.launch.py"), GzSim());
            File.WriteAllText(Path.Combine(outputDir, "ros2_control.launch.py"), Ros2Control());
        }

        private string Display() => $@"# Auto-generated by SW2GZ.
import os
import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('{_in.PackageName}')
    xacro_path = os.path.join(pkg_share, 'urdf', '{_in.XacroFileName}')
    robot_desc = xacro.process_file(xacro_path).toxml()

    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher',
               output='screen', parameters=[{{'robot_description': robot_desc, 'use_sim_time': False}}])
    jsp = Node(package='joint_state_publisher_gui', executable='joint_state_publisher_gui')
    rviz = Node(package='rviz2', executable='rviz2', arguments=[
        '-d', os.path.join(pkg_share, 'config', 'rviz.rviz')])

    return LaunchDescription([rsp, jsp, rviz])
";

        private string GzSim()
        {
            string gzPkg = _in.Profile.Gz == GzVersion.Fortress ? "ros_ign_gazebo" : "ros_gz_sim";
            string spawnExe = "create";
            return $@"# Auto-generated by SW2GZ.
import os
import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, SetEnvironmentVariable
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('{_in.PackageName}')
    xacro_path = os.path.join(pkg_share, 'urdf', '{_in.XacroFileName}')
    robot_desc = xacro.process_file(xacro_path, mappings={{'use_sim': 'true'}}).toxml()
    world_path = os.path.join(pkg_share, 'worlds', '{_in.WorldFileName}')

    set_resource = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH',
        value=os.path.dirname(pkg_share))

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('{gzPkg}'), 'launch', 'gz_sim.launch.py')),
        launch_arguments={{'gz_args': f'-r {{world_path}}'}}.items())

    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher',
               output='screen', parameters=[{{'robot_description': robot_desc, 'use_sim_time': True}}])

    spawn = Node(package='{gzPkg}', executable='{spawnExe}',
                 arguments=['-topic', 'robot_description', '-name', '{_in.PackageName}'])

    return LaunchDescription([set_resource, gz_sim, rsp, spawn])
";
        }

        private string Ros2Control() => @"# Auto-generated by SW2GZ.
from launch import LaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessExit
from launch_ros.actions import Node

def generate_launch_description():
    jsb = Node(package='controller_manager', executable='spawner',
               arguments=['joint_state_broadcaster', '--controller-manager', '/controller_manager'])
    jtc = Node(package='controller_manager', executable='spawner',
               arguments=['joint_trajectory_controller', '--controller-manager', '/controller_manager'])
    return LaunchDescription([
        jsb,
        RegisterEventHandler(OnProcessExit(target_action=jsb, on_exit=[jtc])),
    ])
";
    }
}
