/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.

Emits the three launch.py files for the exported package.

Fixes v1.0 export bugs:
  5 — GZ_SIM_SYSTEM_PLUGIN_PATH was never set → libgz_ros2_control-system.so
      not found by gz sim → controller_manager never spawned.
  6 — spawn -name argument now matches the model name used in
      config/ros_gz_bridge.yaml topic paths.
  7 — parameter_bridge node now launched alongside gz sim so /clock is
      bridged and use_sim_time:=True actually advances.

Locked to ROS 2 Jazzy + Gz Sim Harmonic. ros_gz_sim is the spawn package.
*/
using System;

namespace SW2GZ.Ros2
{
    public static class LaunchPyWriter
    {
        public static string Display(string packageName)
        {
            Guard(packageName);
            return $@"# Auto-generated by SW2GZ.
import os
import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('{packageName}')
    xacro_path = os.path.join(pkg_share, 'urdf', '{packageName}.urdf.xacro')
    robot_desc = xacro.process_file(xacro_path).toxml()

    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher',
               output='screen',
               parameters=[{{'robot_description': robot_desc, 'use_sim_time': False}}])
    jsp = Node(package='joint_state_publisher_gui', executable='joint_state_publisher_gui')
    rviz = Node(package='rviz2', executable='rviz2',
                arguments=['-d', os.path.join(pkg_share, 'config', 'rviz.rviz')])

    return LaunchDescription([rsp, jsp, rviz])
";
        }

        // Single-command full-stack launch for ROS 2 Jazzy + Gz Harmonic:
        //   Gz Harmonic empty world  +  robot_state_publisher  +  spawn robot
        //   +  parameter_bridge  +  joint_state_broadcaster + joint_trajectory_controller
        // The controller spawners chain off `spawn` via OnProcessExit so the
        // controller_manager (running inside the gz_ros2_control system plugin)
        // is up before we ask it to load controllers. Gz viewport is the only
        // 3D view — no rviz required.
        public static string GzSim(string packageName) => GzSim(packageName, 0, 0, 0);

        /// rpy applied to the `ros_gz_sim create` spawn args (-R -P -Y). Used to
        /// orient the robot at spawn time when the URDF has NO world link
        /// embedding the SW→ROS rotation (the REP-105 default).
        public static string GzSim(string packageName, double roll, double pitch, double yaw)
        {
            Guard(packageName);
            string r = roll.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            string p = pitch.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            string y = yaw.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            return $@"# Auto-generated by SW2GZ.
# ROS 2 Jazzy + Gz Harmonic single-command bringup.
import os
import xacro
from ament_index_python.packages import get_package_prefix, get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, RegisterEventHandler, SetEnvironmentVariable
from launch.event_handlers import OnProcessExit
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('{packageName}')
    xacro_path = os.path.join(pkg_share, 'urdf', '{packageName}.urdf.xacro')
    robot_desc = xacro.process_file(xacro_path, mappings={{'use_sim': 'true'}}).toxml()
    world_path = os.path.join(pkg_share, 'worlds', 'empty.sdf')

    set_system_plugin_path = SetEnvironmentVariable(
        name='GZ_SIM_SYSTEM_PLUGIN_PATH',
        value=os.path.join(get_package_prefix('gz_ros2_control'), 'lib'))

    set_resource_path = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH',
        value=os.path.dirname(pkg_share))

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('ros_gz_sim'), 'launch', 'gz_sim.launch.py')),
        launch_arguments=[('gz_args', '-r ' + world_path)])

    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher',
               output='screen',
               parameters=[{{'robot_description': robot_desc, 'use_sim_time': True}}])

    spawn = Node(package='ros_gz_sim', executable='create',
                 arguments=['-topic', 'robot_description', '-name', '{packageName}',
                            '-R', '{r}', '-P', '{p}', '-Y', '{y}'],
                 output='screen')

    bridge = Node(package='ros_gz_bridge', executable='parameter_bridge',
                  parameters=[{{'config_file': os.path.join(
                      pkg_share, 'config/ros_gz_bridge.yaml')}}],
                  output='screen')

    jsb_spawner = Node(package='controller_manager', executable='spawner',
                       arguments=['joint_state_broadcaster',
                                  '--controller-manager', '/controller_manager'],
                       output='screen')

    jtc_spawner = Node(package='controller_manager', executable='spawner',
                       arguments=['joint_trajectory_controller',
                                  '--controller-manager', '/controller_manager'],
                       output='screen')

    # Chain: spawn robot -> load JSB -> load JTC. OnProcessExit fires once the
    # spawner exits successfully (it's a one-shot CLI that registers + quits).
    load_jsb_after_spawn = RegisterEventHandler(OnProcessExit(
        target_action=spawn, on_exit=[jsb_spawner]))
    load_jtc_after_jsb = RegisterEventHandler(OnProcessExit(
        target_action=jsb_spawner, on_exit=[jtc_spawner]))

    return LaunchDescription([
        set_system_plugin_path,
        set_resource_path,
        gz_sim,
        rsp,
        spawn,
        bridge,
        load_jsb_after_spawn,
        load_jtc_after_jsb,
    ])
";
        }

        // Model-only spawn launch: starts Gz Harmonic with the empty world, runs
        // robot_state_publisher from the xacro, spawns the bare robot, and bridges
        // /clock so sim time advances. No ros2_control / gz_ros2_control plugin.
        public static string GzSimModelOnly(string packageName) => GzSimModelOnly(packageName, 0, 0, 0);

        public static string GzSimModelOnly(string packageName, double roll, double pitch, double yaw)
        {
            Guard(packageName);
            string r = roll.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            string p = pitch.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            string y = yaw.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            return $@"# Auto-generated by SW2GZ (model-only).
import os
import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, SetEnvironmentVariable
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('{packageName}')
    xacro_path = os.path.join(pkg_share, 'urdf', '{packageName}.urdf.xacro')
    robot_desc = xacro.process_file(xacro_path, mappings={{'use_sim': 'true'}}).toxml()
    world_path = os.path.join(pkg_share, 'worlds', 'empty.sdf')

    set_resource_path = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH',
        value=os.path.dirname(pkg_share))

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('ros_gz_sim'), 'launch', 'gz_sim.launch.py')),
        launch_arguments=[('gz_args', '-r ' + world_path)])

    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher',
               output='screen',
               parameters=[{{'robot_description': robot_desc, 'use_sim_time': True}}])

    spawn = Node(package='ros_gz_sim', executable='create',
                 arguments=['-topic', 'robot_description', '-name', '{packageName}',
                            '-R', '{r}', '-P', '{p}', '-Y', '{y}'],
                 output='screen')

    clock_bridge = Node(package='ros_gz_bridge', executable='parameter_bridge',
                        arguments=['/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock'],
                        output='screen')

    return LaunchDescription([
        set_resource_path,
        gz_sim,
        rsp,
        spawn,
        clock_bridge,
    ])
";
        }

        // GZ Asset: start Gz Harmonic with the empty world, then spawn the gz model
        // (models/<pkg>/model.sdf) into it. No ros2_control, no bridge.
        // SDF-mode coordinate rotation rides on the spawn command's -R -P -Y
        // args. URDF-mode applies it in the world_to_root joint instead.
        public static string GzAsset(string packageName, double roll = 0, double pitch = 0, double yaw = 0)
        {
            Guard(packageName);
            string r = roll.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            string p = pitch.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            string y = yaw.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
            return $@"# Auto-generated by SW2GZ (gz asset).
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, SetEnvironmentVariable
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('{packageName}')
    models_dir = os.path.join(pkg_share, 'models')
    world_path = os.path.join(pkg_share, 'worlds', 'empty.sdf')
    model_sdf = os.path.join(models_dir, '{packageName}', 'model.sdf')

    set_resource_path = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH', value=models_dir)

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('ros_gz_sim'), 'launch', 'gz_sim.launch.py')),
        launch_arguments=[('gz_args', '-r ' + world_path)])

    spawn = Node(package='ros_gz_sim', executable='create',
                 arguments=['-name', '{packageName}', '-file', model_sdf,
                            '-R', '{r}', '-P', '{p}', '-Y', '{y}'],
                 output='screen')

    return LaunchDescription([set_resource_path, gz_sim, spawn])
";
        }

        // GZ World: the model is already <include>d in the world, so just load it.
        public static string GzWorld(string packageName, string worldName)
        {
            Guard(packageName);
            if (string.IsNullOrWhiteSpace(worldName))
                throw new ArgumentException("worldName must not be null or whitespace.", nameof(worldName));
            return $@"# Auto-generated by SW2GZ (gz world).
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, SetEnvironmentVariable
from launch.launch_description_sources import PythonLaunchDescriptionSource

def generate_launch_description():
    pkg_share = get_package_share_directory('{packageName}')
    models_dir = os.path.join(pkg_share, 'models')
    world_path = os.path.join(pkg_share, 'worlds', '{worldName}.sdf')

    set_resource_path = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH', value=models_dir)

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('ros_gz_sim'), 'launch', 'gz_sim.launch.py')),
        launch_arguments=[('gz_args', '-r ' + world_path)])

    return LaunchDescription([set_resource_path, gz_sim])
";
        }

        public static string Ros2Control(string packageName)
        {
            Guard(packageName);
            return @"# Auto-generated by SW2GZ.
from launch import LaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessExit
from launch_ros.actions import Node

def generate_launch_description():
    jsb = Node(package='controller_manager', executable='spawner',
               arguments=['joint_state_broadcaster', '--controller-manager', '/controller_manager'])
    jtc = Node(package='controller_manager', executable='spawner',
               arguments=['joint_trajectory_controller', '--controller-manager', '/controller_manager'])
    return LaunchDescription([
        jsb,
        RegisterEventHandler(OnProcessExit(target_action=jsb, on_exit=[jtc])),
    ])
";
        }

        private static void Guard(string pkg)
        {
            if (string.IsNullOrWhiteSpace(pkg))
                throw new ArgumentException("packageName must not be null or whitespace.", nameof(pkg));
        }
    }
}
