/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.
*/
using System.IO;
using System.Xml.Linq;

namespace SW2GZ.Ros2
{
    public class PackageXmlV3Writer
    {
        public class Input
        {
            public string PackageName { get; set; }
            public string Version { get; set; } = "0.1.0";
            public string Description { get; set; } = "Auto-generated by SW2GZ";
            public string Maintainer { get; set; } = "TODO";
            public string MaintainerEmail { get; set; } = "TODO@example.com";
            public string License { get; set; } = "Apache-2.0";
            public TargetProfile Profile { get; set; }
        }

        private readonly Input _input;
        public PackageXmlV3Writer(Input input) { _input = input; }

        public void Write(string outputDir)
        {
            Directory.CreateDirectory(outputDir);
            // Fortress era used "ros_ign_*" + "ign_ros2_control"; Harmonic+ use "ros_gz_*" + "gz_ros2_control"
            string rosSim    = _input.Profile.Gz == GzVersion.Fortress ? "ros_ign_gazebo"   : "ros_gz_sim";
            string rosBridge = _input.Profile.Gz == GzVersion.Fortress ? "ros_ign_bridge"   : "ros_gz_bridge";
            string control   = _input.Profile.Gz == GzVersion.Fortress ? "ign_ros2_control" : "gz_ros2_control";

            var doc = new XDocument(
                new XDeclaration("1.0", "utf-8", null),
                new XElement("package",
                    new XAttribute("format", "3"),
                    new XElement("name", _input.PackageName),
                    new XElement("version", _input.Version),
                    new XElement("description", _input.Description),
                    new XElement("maintainer",
                        new XAttribute("email", _input.MaintainerEmail),
                        _input.Maintainer),
                    new XElement("license", _input.License),
                    new XElement("buildtool_depend", "ament_cmake"),
                    new XElement("exec_depend", "robot_state_publisher"),
                    new XElement("exec_depend", "joint_state_publisher_gui"),
                    new XElement("exec_depend", "xacro"),
                    new XElement("exec_depend", "rviz2"),
                    new XElement("exec_depend", rosSim),
                    new XElement("exec_depend", rosBridge),
                    new XElement("exec_depend", control),
                    new XElement("exec_depend", "ros2_control"),
                    new XElement("exec_depend", "ros2_controllers"),
                    new XElement("export",
                        new XElement("build_type", "ament_cmake"),
                        new XElement("architecture_independent"))));

            doc.Save(Path.Combine(outputDir, "package.xml"));
        }
    }
}
