/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.

Emits package.xml format 3 for the exported ROS 2 package. Locked to
Jazzy + Harmonic — drops the v1 TargetProfile branching that picked
ros_ign_* vs ros_gz_* deps. Hard-codes ros_gz_sim + ros_gz_bridge +
gz_ros2_control for Harmonic.
*/
using System;
using System.Xml.Linq;

namespace SW2GZ.Ros2
{
    public sealed record PackageXmlInput(
        string Name,
        string Version,
        string Description,
        string Maintainer,
        string Email,
        string License);

    public static class PackageXmlV3Writer
    {
        public static string Write(PackageXmlInput input)
        {
            if (input == null) throw new ArgumentNullException(nameof(input));
            if (string.IsNullOrWhiteSpace(input.Name))
                throw new ArgumentException("Name must not be null or whitespace.", nameof(input));

            var doc = new XDocument(
                new XDeclaration("1.0", "utf-8", null),
                new XElement("package",
                    new XAttribute("format", "3"),
                    new XElement("name", input.Name),
                    new XElement("version", input.Version ?? "0.0.1"),
                    new XElement("description", input.Description ?? "Auto-generated by SW2GZ"),
                    new XElement("maintainer",
                        new XAttribute("email", input.Email ?? "TODO@example.com"),
                        input.Maintainer ?? "TODO"),
                    new XElement("license", input.License ?? "Apache-2.0"),
                    new XElement("buildtool_depend", "ament_cmake"),
                    new XElement("exec_depend", "robot_state_publisher"),
                    new XElement("exec_depend", "joint_state_publisher_gui"),
                    new XElement("exec_depend", "xacro"),
                    new XElement("exec_depend", "rviz2"),
                    new XElement("exec_depend", "ros_gz_sim"),
                    new XElement("exec_depend", "ros_gz_bridge"),
                    new XElement("exec_depend", "gz_ros2_control"),
                    new XElement("exec_depend", "ros2_control"),
                    new XElement("exec_depend", "ros2_controllers"),
                    new XElement("export",
                        new XElement("build_type", "ament_cmake"),
                        new XElement("architecture_independent"))));

            return doc.Declaration + System.Environment.NewLine + doc.ToString();
        }
    }
}
