/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.
*/
using System.IO;
using System.Text;

namespace SW2GZ.Ros2
{
    public class ReadmeWriter
    {
        private readonly string _pkg;
        private readonly TargetProfile _profile;
        public ReadmeWriter(string pkg, TargetProfile profile) { _pkg = pkg; _profile = profile; }

        public void Write(string outputDir)
        {
            Directory.CreateDirectory(outputDir);
            var sb = new StringBuilder();
            sb.AppendLine($"# {_pkg}");
            sb.AppendLine();
            sb.AppendLine("Auto-generated by **SW2GZ** for ROS 2 **Jazzy** + Gazebo **Harmonic**.");
            sb.AppendLine();
            sb.AppendLine("## What's in this package");
            sb.AppendLine();
            sb.AppendLine("- `urdf/" + _pkg + ".urdf.xacro` — robot description (links, joints, inertia).");
            sb.AppendLine("  Anchored to a `world` link via a fixed joint so it stays put on spawn.");
            sb.AppendLine("- `urdf/inc/ros2_control.xacro` — ros2_control hardware interface backed by");
            sb.AppendLine("  `gz_ros2_control/GazeboSimSystem`. Every joint exposes position command +");
            sb.AppendLine("  position/velocity/effort state.");
            sb.AppendLine("- `urdf/inc/gz.xacro` — Gazebo system plugin (`gz_ros2_control-system`)");
            sb.AppendLine("  loading the controller manager inside the sim.");
            sb.AppendLine("- `urdf/inc/materials.xacro` — named visual materials (if any were tagged).");
            sb.AppendLine("- `config/controllers.yaml` — `joint_state_broadcaster` +");
            sb.AppendLine("  `joint_trajectory_controller` over all joints.");
            sb.AppendLine("- `config/ros_gz_bridge.yaml` — `/clock`, `/joint_states`, `/tf` bridge.");
            sb.AppendLine("- `worlds/empty.sdf` — empty Gz Harmonic world (physics, scene broadcaster,");
            sb.AppendLine("  user commands).");
            sb.AppendLine("- `launch/gz_sim.launch.py` — single-command bringup (see below).");
            sb.AppendLine("- `meshes/` — per-link `.dae` (visual) and `.stl` (collision, convex hull).");
            sb.AppendLine();
            sb.AppendLine("## Build");
            sb.AppendLine();
            sb.AppendLine("```bash");
            sb.AppendLine("cd " + _pkg + "_ws");
            sb.AppendLine("colcon build --symlink-install");
            sb.AppendLine("source install/setup.bash");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("## Run");
            sb.AppendLine();
            sb.AppendLine("```bash");
            sb.AppendLine("ros2 launch " + _pkg + " gz_sim.launch.py");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("That single launch starts:");
            sb.AppendLine();
            sb.AppendLine("1. Gazebo Harmonic with `worlds/empty.sdf` (Gz viewport is the 3D view —");
            sb.AppendLine("   no rviz needed).");
            sb.AppendLine("2. `robot_state_publisher` from the xacro.");
            sb.AppendLine("3. Spawns the robot into Gz.");
            sb.AppendLine("4. `ros_gz_bridge` for clock + joint states + tf.");
            sb.AppendLine("5. `joint_state_broadcaster` spawner, then");
            sb.AppendLine("   `joint_trajectory_controller` spawner (chained after spawn).");
            sb.AppendLine();
            sb.AppendLine("## Command the robot");
            sb.AppendLine();
            sb.AppendLine("```bash");
            sb.AppendLine("ros2 control list_controllers");
            sb.AppendLine("ros2 topic pub --once /joint_trajectory_controller/joint_trajectory \\");
            sb.AppendLine("  trajectory_msgs/msg/JointTrajectory '{joint_names: [...], points: [...]}'");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("## Scope");
            sb.AppendLine();
            sb.AppendLine("Implemented: link geometry + inertia, joint connectivity + type + axis +");
            sb.AppendLine("limits (with safe nonzero defaults), ros2_control wiring, single-command");
            sb.AppendLine("Gz bringup, ros_gz bridge, world anchor.");
            sb.AppendLine();
            sb.AppendLine("Not implemented in this auto-generated package: tuned controller gains,");
            sb.AppendLine("custom worlds, sensor calibration, MoveIt config. Drop those in alongside");
            sb.AppendLine("(this package is meant as a working starting point, not a turnkey app).");
            File.WriteAllText(Path.Combine(outputDir, "README.md"), sb.ToString());
        }
    }
}
