/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.
*/
using System.IO;
using System.Text;

namespace SW2GZ.Ros2
{
    public class ReadmeWriter
    {
        private readonly string _pkg;
        private readonly TargetProfile _profile;
        public ReadmeWriter(string pkg, TargetProfile profile) { _pkg = pkg; _profile = profile; }

        public void Write(string outputDir)
        {
            Directory.CreateDirectory(outputDir);
            var sb = new StringBuilder();
            sb.AppendLine($"# {_pkg}");
            sb.AppendLine();
            sb.AppendLine($"Auto-generated by SW2GZ for ROS 2 **{_profile.Ros2}** + Gz **{_profile.Gz}**.");
            sb.AppendLine();
            sb.AppendLine("## Build");
            sb.AppendLine();
            sb.AppendLine("```bash");
            sb.AppendLine($"cd ~/ros2_ws/src && cp -r /path/to/this/pkg .");
            sb.AppendLine($"cd ~/ros2_ws && colcon build --packages-select {_pkg}");
            sb.AppendLine($"source install/setup.bash");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("## Launch");
            sb.AppendLine();
            sb.AppendLine("```bash");
            sb.AppendLine($"# RViz only (no physics)");
            sb.AppendLine($"ros2 launch {_pkg} display.launch.py");
            sb.AppendLine();
            sb.AppendLine($"# Gz Sim with ros2_control");
            sb.AppendLine($"ros2 launch {_pkg} gz_sim.launch.py");
            sb.AppendLine($"ros2 launch {_pkg} ros2_control.launch.py");
            sb.AppendLine("```");
            File.WriteAllText(Path.Combine(outputDir, "README.md"), sb.ToString());
        }
    }
}
