/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.

Standalone (no-ament) World launch file: brings up Gz Harmonic on the exported
world .sdf plus a ros_gz parameter_bridge. Unlike LaunchPyWriter.GzWorld (which
assumes an installed ament package and uses get_package_share_directory), this
launch resolves OUR files relative to the launch file's own directory, so the
exported folder runs un-built, wherever it is copied:

    ros2 launch <pkg>/launch_world.py

Only ros_gz_sim (an installed ROS package) is still resolved via
get_package_share_directory — our world .sdf and bridge yaml sit next to the
launch file.

Locked to ROS 2 Jazzy + Gz Sim Harmonic. Pairs with WorldBridgeYaml.
*/
using System;

namespace SW2GZ.Ros2
{
    public static class WorldLaunchPyWriter
    {
        // worldFileName is the sibling .sdf name (e.g. "my_world.sdf").
        // teleop adds nothing to the launch itself (the bridge yaml carries the
        // /cmd_vel entry); the flag is accepted for symmetry + future use and to
        // document intent at the call site.
        public static string Write(string worldFileName, bool teleop)
        {
            if (string.IsNullOrWhiteSpace(worldFileName))
                throw new ArgumentException("worldFileName must not be null or whitespace.", nameof(worldFileName));

            return $@"# Auto-generated by SW2GZ (standalone world launch).
# ROS 2 Jazzy + Gz Harmonic. Run with:  ros2 launch <this file>
# Resolves the world .sdf and bridge yaml relative to this file, so the exported
# folder runs un-built wherever it is copied.
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, SetEnvironmentVariable
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

def generate_launch_description():
    here = os.path.dirname(os.path.realpath(__file__))
    world_path = os.path.join(here, '{worldFileName}')
    bridge_config = os.path.join(here, 'ros_gz_bridge.yaml')

    set_resource_path = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH', value=here)

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('ros_gz_sim'), 'launch', 'gz_sim.launch.py')),
        launch_arguments=[('gz_args', '-r ' + world_path)])

    bridge = Node(package='ros_gz_bridge', executable='parameter_bridge',
                  parameters=[{{'config_file': bridge_config}}],
                  output='screen')

    return LaunchDescription([set_resource_path, gz_sim, bridge])
";
        }
    }
}
