# Auto-generated by SW2GZ.
# ROS 2 Jazzy + Gz Harmonic single-command bringup.
import os
import xacro
from ament_index_python.packages import get_package_prefix, get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, RegisterEventHandler, SetEnvironmentVariable
from launch.event_handlers import OnProcessExit
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('full_arm')
    xacro_path = os.path.join(pkg_share, 'urdf', 'full_arm.urdf.xacro')
    robot_desc = xacro.process_file(xacro_path, mappings={'use_sim': 'true'}).toxml()
    world_path = os.path.join(pkg_share, 'worlds', 'empty.sdf')

    set_system_plugin_path = SetEnvironmentVariable(
        name='GZ_SIM_SYSTEM_PLUGIN_PATH',
        value=os.path.join(get_package_prefix('gz_ros2_control'), 'lib'))

    set_resource_path = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH',
        value=os.path.dirname(pkg_share))

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('ros_gz_sim'), 'launch', 'gz_sim.launch.py')),
        launch_arguments=[('gz_args', '-r ' + world_path)])

    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher',
               output='screen',
               parameters=[{'robot_description': robot_desc, 'use_sim_time': True}])

    spawn = Node(package='ros_gz_sim', executable='create',
                 arguments=['-topic', 'robot_description', '-name', 'full_arm'],
                 output='screen')

    bridge = Node(package='ros_gz_bridge', executable='parameter_bridge',
                  parameters=[{'config_file': os.path.join(
                      pkg_share, 'config/ros_gz_bridge.yaml')}],
                  output='screen')

    jsb_spawner = Node(package='controller_manager', executable='spawner',
                       arguments=['joint_state_broadcaster',
                                  '--controller-manager', '/controller_manager'],
                       output='screen')

    jtc_spawner = Node(package='controller_manager', executable='spawner',
                       arguments=['joint_trajectory_controller',
                                  '--controller-manager', '/controller_manager'],
                       output='screen')

    # Chain: spawn robot -> load JSB -> load JTC. OnProcessExit fires once the
    # spawner exits successfully (it's a one-shot CLI that registers + quits).
    load_jsb_after_spawn = RegisterEventHandler(OnProcessExit(
        target_action=spawn, on_exit=[jsb_spawner]))
    load_jtc_after_jsb = RegisterEventHandler(OnProcessExit(
        target_action=jsb_spawner, on_exit=[jtc_spawner]))

    return LaunchDescription([
        set_system_plugin_path,
        set_resource_path,
        gz_sim,
        rsp,
        spawn,
        bridge,
        load_jsb_after_spawn,
        load_jtc_after_jsb,
    ])
