# Auto-generated by SW2GZ.
import os
import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, SetEnvironmentVariable
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = get_package_share_directory('three_dof_arm_description')
    xacro_path = os.path.join(pkg_share, 'urdf', 'three_dof_arm_description.urdf.xacro')
    robot_desc = xacro.process_file(xacro_path, mappings={'use_sim': 'true'}).toxml()
    world_path = os.path.join(pkg_share, 'worlds', 'empty.sdf')

    set_resource = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH',
        value=os.path.dirname(pkg_share))

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('ros_ign_gazebo'), 'launch', 'gz_sim.launch.py')),
        launch_arguments={'gz_args': f'-r {world_path}'}.items())

    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher',
               output='screen', parameters=[{'robot_description': robot_desc, 'use_sim_time': True}])

    spawn = Node(package='ros_ign_gazebo', executable='create',
                 arguments=['-topic', 'robot_description', '-name', 'three_dof_arm_description'])

    return LaunchDescription([set_resource, gz_sim, rsp, spawn])
