# Auto-generated by SW2GZ.
from launch import LaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessExit
from launch_ros.actions import Node

def generate_launch_description():
    jsb = Node(package='controller_manager', executable='spawner',
               arguments=['joint_state_broadcaster', '--controller-manager', '/controller_manager'])
    jtc = Node(package='controller_manager', executable='spawner',
               arguments=['joint_trajectory_controller', '--controller-manager', '/controller_manager'])
    return LaunchDescription([
        jsb,
        RegisterEventHandler(OnProcessExit(target_action=jsb, on_exit=[jtc])),
    ])
