/*
Copyright (c) 2026 Aryan Arlikar. MIT License — see CONTRIBUTING.md.
*/
using System.Collections.Generic;
using System.IO;
using SW2GZ.Gz;
using SW2GZ.Ros2;

namespace SW2GZ.URDFExport
{
    public class Ros2Package
    {
        public class Options
        {
            public string PackageName { get; set; }
            public string Maintainer { get; set; } = "TODO";
            public string MaintainerEmail { get; set; } = "TODO@example.com";
            public string License { get; set; } = "Apache-2.0";
            public IReadOnlyList<string> JointNames { get; set; }
            public TargetProfile Profile { get; set; }
            public string UrdfBodyXml { get; set; }
        }

        private readonly Options _opt;
        public Ros2Package(Options opt) { _opt = opt; }

        public void Write(string outputDir)
        {
            Directory.CreateDirectory(outputDir);
            foreach (var d in new[] { "urdf", "urdf/inc", "config", "launch", "worlds", "meshes/visual", "meshes/collision" })
                Directory.CreateDirectory(Path.Combine(outputDir, d));

            string pkgXml = PackageXmlV3Writer.Write(new PackageXmlInput(
                _opt.PackageName,
                "0.1.0",
                "Auto-generated by SW2GZ",
                _opt.Maintainer,
                _opt.MaintainerEmail,
                _opt.License));
            File.WriteAllText(Path.Combine(outputDir, "package.xml"), pkgXml);

            string cmake = AmentCMakeWriter.Write(new AmentCMakeInput(_opt.PackageName, hasMeshes: true));
            File.WriteAllText(Path.Combine(outputDir, "CMakeLists.txt"), cmake);

            File.WriteAllText(
                Path.Combine(outputDir, "urdf", $"{_opt.PackageName}.urdf.xacro"),
                XacroWriter.Write(_opt.PackageName, _opt.UrdfBodyXml));

            // TODO(materials): introduce a MaterialsXacro writer in a later task.
            File.WriteAllText(Path.Combine(outputDir, "urdf", "inc", "materials.xacro"),
                "<?xml version=\"1.0\"?>\n<robot xmlns:xacro=\"http://www.ros.org/wiki/xacro\">\n  <!-- Named materials populated by SW2GZ. -->\n</robot>\n");

            string ros2CtrlXacro = Ros2ControlWriter.Write(_opt.PackageName, _opt.JointNames);
            File.WriteAllText(Path.Combine(outputDir, "urdf", "inc", "ros2_control.xacro"), ros2CtrlXacro);

            string gzXacro = GzPluginTags.WriteGzRos2ControlXacro(_opt.PackageName);
            File.WriteAllText(Path.Combine(outputDir, "urdf", "inc", "gz.xacro"), gzXacro);

            // TODO(T18): replace with dedicated ControllersYaml writer.
            // Inline placeholder so config/controllers.yaml exists for launch files.
            var yaml = new System.Text.StringBuilder();
            yaml.AppendLine("controller_manager:");
            yaml.AppendLine("  ros__parameters:");
            yaml.AppendLine("    update_rate: 100");
            yaml.AppendLine("    joint_state_broadcaster:");
            yaml.AppendLine("      type: joint_state_broadcaster/JointStateBroadcaster");
            yaml.AppendLine("    joint_trajectory_controller:");
            yaml.AppendLine("      type: joint_trajectory_controller/JointTrajectoryController");
            yaml.AppendLine();
            yaml.AppendLine("joint_trajectory_controller:");
            yaml.AppendLine("  ros__parameters:");
            yaml.AppendLine("    joints:");
            foreach (var j in _opt.JointNames) yaml.AppendLine($"      - {j}");
            yaml.AppendLine("    command_interfaces:");
            yaml.AppendLine("      - position");
            yaml.AppendLine("    state_interfaces:");
            yaml.AppendLine("      - position");
            yaml.AppendLine("      - velocity");
            File.WriteAllText(Path.Combine(outputDir, "config", "controllers.yaml"), yaml.ToString());

            new RvizConfigWriter().Write(Path.Combine(outputDir, "config"), "rviz.rviz");
            new RosGzBridgeYaml().Write(Path.Combine(outputDir, "config"), "ros_gz_bridge.yaml");

            string launchDir = Path.Combine(outputDir, "launch");
            File.WriteAllText(Path.Combine(launchDir, "display.launch.py"),      LaunchPyWriter.Display(_opt.PackageName));
            File.WriteAllText(Path.Combine(launchDir, "gz_sim.launch.py"),       LaunchPyWriter.GzSim(_opt.PackageName));
            File.WriteAllText(Path.Combine(launchDir, "ros2_control.launch.py"), LaunchPyWriter.Ros2Control(_opt.PackageName));

            string worldSdf = SdfWorldWriter.Write(new SdfWorldInput("empty"));
            File.WriteAllText(Path.Combine(outputDir, "worlds", "empty.sdf"), worldSdf);

            new ReadmeWriter(_opt.PackageName, _opt.Profile).Write(outputDir);

            File.WriteAllText(Path.Combine(outputDir, ".gitignore"),
                "build/\ninstall/\nlog/\n*.user\n");
        }
    }
}
