; Auto-generated by Aryan Arlikar. MIT License.
; Build with: ISCC.exe installer\SW2GZ.iss
#define MyAppName        "SW2GZ"
#define MyAppVersion     "1.0.0"
#define MyAppPublisher   "Aryan Arlikar"
; Replace this with $COM_GUID generated in Phase 0 Task 0.4 (see .sw2gz-guids.txt).
#define AddinGuid        "{34fad620-2a46-4ba6-9f5f-1dfefde894c7}"

[Setup]
AppId={{#AddinGuid}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\SW2GZ
DefaultGroupName=SW2GZ
DisableProgramGroupPage=yes
OutputDir=Output
OutputBaseFilename=SW2GZ-Setup-{#MyAppVersion}
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64
PrivilegesRequired=admin

[Files]
Source: "..\SW2GZ\bin\x64\Release\SW2GZ.dll";        DestDir: "{app}"; Flags: ignoreversion
Source: "..\SW2GZ\bin\x64\Release\SW2GZ.dll.config"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "..\SW2GZ\bin\x64\Release\*.dll";            DestDir: "{app}"; Flags: ignoreversion

[Run]
Filename: "{win}\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe"; Parameters: "/codebase ""{app}\SW2GZ.dll"""; StatusMsg: "Registering SW2GZ add-in for SolidWorks..."; Flags: runhidden

[UninstallRun]
Filename: "{win}\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe"; Parameters: "/u ""{app}\SW2GZ.dll"""; Flags: runhidden
