; SW2GZ installer — auto-removes previous install, kills SolidWorks if running,
; deploys + registers in one click.
; Build: ISCC.exe /DMyAppVersion=<version> installer\SW2GZ.iss (see BUILD.md)
#define MyAppName        "SW2GZ"
; MyAppVersion drives AppVersion + the output filename. Pass it explicitly at
; build time so it tracks the git tag being released, e.g.:
;   ISCC.exe /DMyAppVersion=2.8.0 installer\SW2GZ.iss
; (BUILD.md and .github/workflows/release.yml derive this from `git describe
; --tags`.) The fallback below is only for ad-hoc local builds without /D —
; bump it when it drifts too far behind the latest tag.
#ifndef MyAppVersion
  #define MyAppVersion "2.8.3"
#endif
#define MyAppPublisher   "Aryan Arlikar"
; SW2GZ COM addin GUID (matches HKLM\SOFTWARE\SolidWorks\Addins\{...}).
#define AddinGuid        "{34fad620-2a46-4ba6-9f5f-1dfefde894c7}"

[Setup]
; {{#AddinGuid} -> literal {GUID}: the leading {{ escapes to one {, the preprocessor
; emits the brace-wrapped GUID, giving a clean AppId of {GUID} (NOT {GUID}}). The
; uninstall key is then {GUID}_is1, which GetUninstallerPath below looks up correctly.
AppId={{#AddinGuid}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\SW2GZ
DefaultGroupName=SW2GZ
DisableProgramGroupPage=yes
OutputDir=Output
OutputBaseFilename=SW2GZ-Setup-{#MyAppVersion}
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin
; Close SolidWorks automatically if it's running — DLL is locked while SW holds the addin.
; The [Code] InitializeSetup hook also runs taskkill /F as a hard backstop.
CloseApplications=force
RestartApplications=no

[Files]
Source: "..\SW2GZ\bin\x64\Release\SW2GZ.dll";        DestDir: "{app}"; Flags: ignoreversion
Source: "..\SW2GZ\bin\x64\Release\SW2GZ.dll.config"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Ship runtime dependency DLLs, but NEVER redistribute:
;   solidworkstools.dll  -> Dassault Systemes' property, already present on every machine that has SolidWorks.
;   xunit* / Moq / Castle.Core / *TestPlatform*  -> test-only deps, not needed at runtime.
Source: "..\SW2GZ\bin\x64\Release\*.dll";            DestDir: "{app}"; Flags: ignoreversion; Excludes: "solidworkstools.dll,xunit*.dll,Moq.dll,Castle.Core.dll,Microsoft.VisualStudio.TestPlatform*.dll"
; Ribbon icon set (PNG strip + per-size icons) generated by
; scripts\GenerateIcons.ps1. Sw2gzIconList() / Sw2gzStripIconList() in
; SwAddin.cs return paths under {app}\images\ - without these the ribbon
; falls back to the generic blue (i) placeholder for every command.
Source: "..\SW2GZ\bin\x64\Release\images\*";         DestDir: "{app}\images"; Flags: ignoreversion
; Browser preview assets (three.js + urdf-loader SPA). PreviewServer.cs
; reads "{app}\preview\index.html" at runtime and hosts it on a random
; 127.0.0.1 port. No node / npm install — three.js + urdf-loader load
; from unpkg.com via the page's importmap on first browser open, then
; cache locally. Only external requirement is internet access for that
; first load on each machine.
Source: "..\SW2GZ\bin\x64\Release\preview\*";        DestDir: "{app}\preview"; Flags: ignoreversion recursesubdirs createallsubdirs

[InstallDelete]
; Wipe stale binaries from the install dir before laying down the new build.
Type: filesandordirs; Name: "{app}\*"

; RegAsm registration runs in [Code] (CurStepChanged/ssPostInstall) — it must execute
; AFTER solidworkstools.dll is copied next to SW2GZ.dll (see CopyLocalSolidWorksTools).
; RegAsm has to load the assembly to register it, and the assembly references SolidWorksTools.

[UninstallRun]
Filename: "{win}\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe"; Parameters: "/u ""{app}\SW2GZ.dll"""; Flags: runhidden runascurrentuser; RunOnceId: "Sw2gzRegasmUnregister"

[UninstallDelete]
; Remove the locally-copied solidworkstools.dll and the (now-empty) install dir.
Type: filesandordirs; Name: "{app}"

[Code]
{ ---------- Detect + silently uninstall any previous SW2GZ install. ---------- }
function GetUninstallerPath: string;
var
  sUnInstPath: string;
  sUnInstallString: string;
begin
  Result := '';
  // Literal Pascal string -- NO ExpandConstant. The #AddinGuid substitution
  // happens at compile time; passing the resulting brace-wrapped GUID through
  // ExpandConstant would make Inno try to parse it as a runtime constant.
  sUnInstPath := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#AddinGuid}_is1';
  sUnInstallString := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
  Result := sUnInstallString;
end;

function StopSolidWorks: Integer;
var
  iResult: Integer;
begin
  Result := 0;
  { Try to close SOLIDWORKS gracefully via taskkill; ignore failures (it may not be running). }
  Exec(ExpandConstant('{cmd}'), '/C taskkill /IM SLDWORKS.exe /T /F >NUL 2>NUL', '', SW_HIDE, ewWaitUntilTerminated, iResult);
end;

function InitializeSetup: Boolean;
var
  sUninstaller: string;
  iResult: Integer;
begin
  Result := True;
  { Kill any running SolidWorks (DLL is locked while it loads the addin). }
  StopSolidWorks;

  { Find any prior SW2GZ install registered under our AppId and silently uninstall it. }
  sUninstaller := GetUninstallerPath;
  if sUninstaller <> '' then
  begin
    { Strip surrounding quotes Inno records around the path. }
    sUninstaller := RemoveQuotes(sUninstaller);
    if FileExists(sUninstaller) then
    begin
      Exec(sUninstaller,
           '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL',
           '', SW_HIDE, ewWaitUntilTerminated, iResult);
      { Give regasm /u a moment to release any handles before we lay down new bits. }
      Sleep(800);
    end;
  end;
end;

{ ---------- Locate the machine's own solidworkstools.dll (Dassault's). ----------
  We never ship this DLL. RegAsm must load SW2GZ.dll to register it, and SW2GZ.dll
  references the SolidWorksTools assembly, so the DLL has to be resolvable. Every
  target machine already has SolidWorks installed, so we source it from there.

  Issue #2: a hardcoded "SOLIDWORKS Corp\SOLIDWORKS\" path misses machines where
  Windows suffixed the folder ("SOLIDWORKS (2)\") because an older/leftover
  install already occupied the plain name (seen on a Student Edition upgrade).
  Resolve via the actual registered SolidWorks.Application COM server first —
  that's the one source of truth unaffected by folder naming/versioning — then
  fall back to a wildcard folder scan, then the old fixed guesses. }
function GetSolidWorksToolsDllViaCom: string;
var
  sClsid, sServerPath, sExeDir: string;
  iExtPos: Integer;
begin
  Result := '';
  if not RegQueryStringValue(HKCR, 'SldWorks.Application\CLSID', '', sClsid) then
    exit;
  if not RegQueryStringValue(HKCR, 'CLSID\' + sClsid + '\LocalServer32', '', sServerPath) then
    exit;
  { Value is usually just the .exe path, sometimes quoted or with trailing switches
    (e.g. "C:\...\SLDWORKS.EXE" /Automation). Trim to the .exe path itself. }
  sServerPath := RemoveQuotes(Trim(sServerPath));
  iExtPos := Pos('.exe', LowerCase(sServerPath));
  if iExtPos > 0 then
    sServerPath := Copy(sServerPath, 1, iExtPos + 3);
  sExeDir := ExtractFileDir(sServerPath);
  if FileExists(AddBackslash(sExeDir) + 'solidworkstools.dll') then
    Result := AddBackslash(sExeDir) + 'solidworkstools.dll';
end;

function GetSolidWorksToolsDllViaFolderScan(const sProgramFiles: string): string;
var
  sBaseDir, sCandidate: string;
  FindRec: TFindRec;
begin
  Result := '';
  sBaseDir := sProgramFiles + '\SOLIDWORKS Corp\';
  if not DirExists(sBaseDir) then
    exit;
  if FindFirst(sBaseDir + 'SOLIDWORKS*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
        begin
          sCandidate := sBaseDir + FindRec.Name + '\solidworkstools.dll';
          if FileExists(sCandidate) then
          begin
            Result := sCandidate;
            break;
          end;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

function GetSolidWorksToolsDll: string;
var
  sRegPath: string;
begin
  Result := GetSolidWorksToolsDllViaCom;
  if Result <> '' then
    exit;

  Result := GetSolidWorksToolsDllViaFolderScan(ExpandConstant('{commonpf}'));
  if Result <> '' then
    exit;
  Result := GetSolidWorksToolsDllViaFolderScan(ExpandConstant('{commonpf32}'));
  if Result <> '' then
    exit;

  { Last-resort fixed guesses (kept for machines the above two somehow miss). }
  if FileExists(ExpandConstant('{commonpf}\SOLIDWORKS Corp\SOLIDWORKS\solidworkstools.dll')) then
    Result := ExpandConstant('{commonpf}\SOLIDWORKS Corp\SOLIDWORKS\solidworkstools.dll')
  else if FileExists(ExpandConstant('{commonpf32}\SOLIDWORKS Corp\SOLIDWORKS\solidworkstools.dll')) then
    Result := ExpandConstant('{commonpf32}\SOLIDWORKS Corp\SOLIDWORKS\solidworkstools.dll')
  else if RegQueryStringValue(HKLM, 'SOFTWARE\SOLIDWORKS\Setup', 'SolidWorks Folder', sRegPath) then
    if FileExists(AddBackslash(sRegPath) + 'solidworkstools.dll') then
      Result := AddBackslash(sRegPath) + 'solidworkstools.dll';
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  sApp, sTools: string;
  bExecOk: Boolean;
  iResult: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    sApp := ExpandConstant('{app}');
    { Copy the local (already-licensed) solidworkstools.dll next to SW2GZ.dll so RegAsm
      can resolve it. This is a local copy of the user's own file, not redistribution. }
    sTools := GetSolidWorksToolsDll;
    if sTools <> '' then
      CopyFile(sTools, sApp + '\solidworkstools.dll', False)
    else
      { Issue #2: this used to fail silently — files copied fine, RegAsm then couldn't
        resolve SolidWorksTools.dll and the SW2GZ COM add-in never registered, so
        SolidWorks never listed it under Tools > Add-Ins, with no error anywhere. }
      MsgBox('SW2GZ could not locate solidworkstools.dll on this machine, so the ' +
        'SolidWorks Add-In cannot be registered. SolidWorks itself is fine, but ' +
        'SW2GZ will NOT appear in Tools > Add-Ins.' + #13#10#13#10 +
        'Please report this at https://github.com/Aryan01b/SW2GZ/issues, including ' +
        'the folder your SolidWorks installation lives in.', mbError, MB_OK);

    { Register the COM add-in. Must run AFTER the copy above. }
    bExecOk := Exec(ExpandConstant('{win}\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe'),
         '/codebase "' + sApp + '\SW2GZ.dll"', '', SW_HIDE, ewWaitUntilTerminated, iResult);

    if (not bExecOk) or (iResult <> 0) then
      MsgBox('SW2GZ installed its files, but registering the SolidWorks Add-In failed ' +
        '(RegAsm exit code ' + IntToStr(iResult) + '). SW2GZ will NOT appear in ' +
        'Tools > Add-Ins until this is resolved.' + #13#10#13#10 +
        'Please report this at https://github.com/Aryan01b/SW2GZ/issues.',
        mbError, MB_OK);
  end;
end;
